import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/Provider";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ClientWrapper from "@/components/ClientWrapper";
import CategoryService from "@/services/category";
import { AuthModal } from "@/components/AuthModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const categories = await CategoryService.getCategories()

  return (
    <html lang="en">
      <body
        className={`antialiased text-textColor font-semibold bg-LightPrimaryHover`}
      >
        <Provider>
          <ClientWrapper>
            <AuthModal />
            <NavBar categories={categories} />

            {children}

            <Footer />
          </ClientWrapper>
        </Provider>
      </body>
    </html>
  );
}
